<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation :)
* https://wordpress.org/plugins/orbisius-child-theme-creator/
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: http://codex.wordpress.org/Child_Themes#Using_functions.php
*
* Be sure not to define functions, that already exist in the parent theme!
* A common pattern is to prefix function names with the (child) theme name.
* Also if the parent theme supports pluggable functions you can use function_exists( 'put_the_function_name_here' ) checks.
*/

/**
 * Loads parent and child themes' style.css
 */
function orbisius_ct_landscaping_bubble_child_theme_enqueue_styles() {
    $parent_style = 'orbisius_ct_landscaping_bubble_parent_style';
    $parent_base_dir = 'twentyseventeen';

    wp_enqueue_style( $parent_style,
        get_template_directory_uri() . '/style.css',
        array(),
        wp_get_theme( $parent_base_dir ) ? wp_get_theme( $parent_base_dir )->get('Version') : ''
    );

    wp_enqueue_style( $parent_style . '_child_style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
}

add_action( 'wp_enqueue_scripts', 'orbisius_ct_landscaping_bubble_child_theme_enqueue_styles' );


if ( !is_admin() ) { // instruction to only load if it is not the admin area
   // register your script location, dependencies and version
   wp_register_script('custom_script',
       get_bloginfo('stylesheet_directory') . '/js/custom_script.js',
       array('jquery'),
       '1.0' );

   // enqueue the script
   wp_enqueue_script('custom_script');
}

// register custom navs
function register_my_menus() {
  register_nav_menus(
    array(
      'main-nav' => __( 'Main Nav' ),
      'another-menu' => __( 'Another Menu' ),
      'an-extra-menu' => __( 'An Extra Menu' )
    )
  );
}
add_action( 'init', 'register_my_menus' );

// Remove the page-two-column CSS class from the body class in BuddyPress pages
function bp_remove_two_column_body_class($wp_classes) {
    if( function_exists ( 'bp_loaded' ) && !bp_is_blog_page() ) :
        foreach($wp_classes as $key => $value) {
             if ($value == 'page-two-column') unset($wp_classes[$key]);
        }
    endif;
    return $wp_classes;
}
add_filter('body_class', 'bp_remove_two_column_body_class', 20, 2);
